### ISSUE TITLE
Dire Lobby Slots to work like Radiant

### ISSUE THREAD

**Issue by ryndrb** [ryndrb/dota2bot#30]

**Comment by dmknght** [comment]
This issue belongs to `hero_selection.lua` script? I would like to take a look.

**Comment by ryndrb** [comment]
Yeah, it is.

**Comment by ryndrb** [comment]
[scribble; not a priority]

[1] Human Player ID does not get "incremented" when switching to Dire slots. That is, given lobby slots:

|Radiant| Dire|
|:-------:|:-----:|
| 0         | 5
| 1         | 6
| 2         | 7
| 3         | 8
| 4         | 9

where each row represents lobby slots. If a human chooses Radiant, their ID will be between **0-4**, respectively. But if they chooses Dire, their ID will remain between **0-4**. For example, Slot 1, their ID will be **0**, "instead" of 5. And the Radiant IDs will get shifted as follows:

(If human chooses Dire slot 1)
|Radiant| Dire|
|:-------:|:-----:|
| 1         | _**0**_
| 2         | 6
| 3         | 7
| 4         | 8
| 5         | 9

This applies to each slot on Dire, (and Radiant IDs get's shifted accordingly). Thanks to Phraggers on the PhalanxBot workshop comments for providing insight.

Since the way this script assign roles according to lobby slot:
GetTeamPlayers(team)[1-5] returns each ID from Slot 1->5. This works fine on Radiant, since if human chooses Slot 5, they will be on Slot 5. But if they choose that on Dire, they will get shifted to Slot 1, _always_. This applies to all the slots on Dire, which messes up role assignments etc,.

[2] Did minor testing, and it seems easy to fix lane assignments and such when a human is on Dire by shuffling the ID table accordingly before hero selection.

[3] ^ After implementing, some weird behaviour "after" (<- not sure yet..) the laning phase where bots continuously retreating to the fountain, etc,. Roles were fine.

[4] ...

**Comment by dmknght** [comment]
```
[2] Did minor testing, and it seems easy to fix lane assignments and such when a human is on Dire by shuffling the ID table accordingly before hero selection.
```
Oh looks like root-cause is in this line `for i, id in pairs( nIDs )` (L822).

```
[3] ^ After implementing, some weird behaviour "after" (<- not sure yet..) the laning phase where bots continuously retreating to the fountain, etc,. Roles were fine.
```
That sounds odd. Since this change could make unstable behaviour of bots, should we test it in a different branch? I might have some free time this weekend so I would like to test this change. And I could try adding hero selection for other game modes (like captain mode) if you want. I tried that with Beginner AI before (based on `Furious Puppy` as I remember).

**Comment by ryndrb** [comment]
[scribble; code]

[4] Working.. I think?

hero_selection
```lua
-- init IDs for Dire
	local nIDs = GetTeamPlayers(GetTeam())
	if GetTeam() == TEAM_DIRE
	then
		local sHuman = {}
		for _, id in pairs(GetTeamPlayers(GetTeam()))
		do
			if not IsPlayerBot(id)
			then
				table.insert(sHuman, id)
			end
		end

		if #sHuman > 0
		then
			local nBotIDs = {5, 6, 7, 8, 9}
			nIDs = {}

			for i = 1, #nBotIDs do table.insert(nIDs, nBotIDs[i]) end

			-- Map it directly
			for i = 1, #sHuman
			do
				for j = 1, 5
				do
					if sHuman[i] + 5 == nBotIDs[j]
					then
						nIDs[j] = sHuman[i]
					end
				end
			end

			-- "Shift" > 4
			for i = #nIDs, 1, -1
			do
				local hCount = 0
				if nIDs[i] > 4
				then
					for j = 1, #nIDs
					do
						if  nIDs[j + i] ~= nil
						and nIDs[j + i] < 5
						then
							hCount = hCount + 1
						end
					end

					nIDs[i] = nIDs[i] + hCount
				end
			end

			local pRoles = {
				[nIDs[1]] = LANE_MID,
				[nIDs[2]] = LANE_BOT,
				[nIDs[3]] = LANE_TOP,
				[nIDs[4]] = LANE_TOP,
				[nIDs[5]] = LANE_BOT,
			}

                        -- Update Lane Roles
			local temp = {}
			for i, v in ipairs(nIDs) do temp[i] = v end

			table.sort(temp)

			tLaneAssignList = {
				[1] = pRoles[temp[1]],
				[2] = pRoles[temp[2]],
				[3] = pRoles[temp[3]],
				[4] = pRoles[temp[4]],
				[5] = pRoles[temp[5]],
			}
		end
	end
``` 

jmz_func
```lua
-- Override this func for the script to use
local orig_GetTeamPlayers = GetTeamPlayers

function GetTeamPlayers()
	local nIDs = orig_GetTeamPlayers(GetTeam())
	if GetTeam() == TEAM_DIRE
	then
		local sHuman = {}
		for _, id in pairs(orig_GetTeamPlayers(GetTeam()))
		do
			if not IsPlayerBot(id)
			then
				table.insert(sHuman, id)
			end
		end

		if #sHuman > 0
		then
			local nBotIDs = {5, 6, 7, 8, 9}
			nIDs = {}

			for i = 1, #nBotIDs do table.insert(nIDs, nBotIDs[i]) end

			-- Map it directly
			for i = 1, #sHuman
			do
				for j = 1, 5
				do
					if sHuman[i] + 5 == nBotIDs[j]
					then
						nIDs[j] = sHuman[i]
					end
				end
			end

			-- "Shift" > 4
			for i = #nIDs, 1, -1
			do
				local hCount = 0
				if nIDs[i] > 4
				then
					for j = 1, #nIDs
					do
						if  nIDs[j + i] ~= nil
						and nIDs[j + i] < 5
						then
							hCount = hCount + 1
						end
					end

					nIDs[i] = nIDs[i] + hCount
				end
			end

			return nIDs
		else
			return orig_GetTeamPlayers(GetTeam())
		end
	else
		return orig_GetTeamPlayers(GetTeam())
	end
end
``` 

[5] ^ Works when testing.

**Comment by dmknght** [comment]
Hello @ryndrb I'm still available, but i'm not so sure which code block should I add / replace for `hero_selection.lua`? Meanwhile I was searching for my old patch, adding CM Mode into beginner AI however beginner AI on workshop disabled all comments and discussions, hence my topic went in vain LoL.

**Comment by dmknght** [comment]
I'm testing it. Everything seems fine for me. I'm waiting until 10 mins to see the if there's any problem after laning phase

**Comment by dmknght** [comment]
Everything is fine on my side. Great work!
