### ISSUE TITLE
A way to fix Valve bug for the new bug buggy heroes

### ISSUE THREAD

**Issue by forest0xia** [ryndrb/dota2bot#45]
As we know there are heroes like Dark Willow, Elder Titan, Hoodwink, Marci, Muerta, Primal Beast.

They are buggy in a way they do not know where to go in lanes and keep going to mid or feeding into towers. 

This is because they do not have a correct target location to go for the lane front they got assigned for. And they by default go to the enemy's base. 

We can change this behavior by editing the laning generic logic desire to make those heroes less desirable for laning or point them to the correct location for laning. Can do this with farming logic as well that we decrease the laning part and increase the farming logic to stay in the correct lane front location. 

There can be multiple options, and I'm sure this is a solvable problem without Valve fixing their shitty code

**Comment by ryndrb** [comment]
I've only tested the buggy heroes before during the laning phase (<10 minutes or laning mode). Is laning mode the only one affected? I'm sure heroes like Hoodwink don't really engage (Attack mode), etc,.

**Comment by forest0xia** [comment]
they all have the same problem where in laning phase there's about 50% chance they can act dumb by trying to go enemy base and then try to farm back and forth. in any other phases after laning, they randomly ack dumb again because bots can be picking up laning at any point. and the main issue is they do not have a valid pushing target location. as soon as we give them a better location, they act like normal.

**Comment by forest0xia** [comment]
your concern about other modes is right. those bots may not have all the default modes from Valve missing - if we dont override the mode, the mode may get lost.
