### ISSUE TITLE
7.37 bug fix for Life stealer and faceless void

### ISSUE THREAD

**Issue by forest0xia** [ryndrb/dota2bot#47]
As we know they were bugged due to missing abilities. But using the Buff mode can fix this problem for the bots - just add abilities back to the bots.

BTW, the Buff mode does not work if you input the command in hero selection phase. Can be better if we can use it the same way as Fretbots.

**Comment by ryndrb** [comment]
I've seen stuff on LS and FV on [here](https://github.com/ValveSoftware/Dota2-Gameplay/issues) and Reddit regarding this issue which weren't bots related, so I thought Valve might fix it with after patch updates. But it's been a while and they just don't care lol.

And the Buff commands were setup to be inputted after the map has loaded.

**Comment by forest0xia** [comment]
It can take a long while for that to get fixed. I don't even care if they care about it or not. They fail their job too frequently especially when it comes to bot logics. We can expect to have more such issues in future.

It's easy to modify Buff to get loaded anytime. Anyways. You can resolve this issue now as I've done the fix myself and this is just a note to you for the same fix. If you don't want to improve the script the way I suggest that's totally fine and expected.

Thanks
