### ISSUE TITLE
How to change Slots while playing LAN

### ISSUE THREAD

**Issue by andre1891** [ryndrb/dota2bot#51]
Hello,
Is there any chance to give the opportuny to chance the Lanes the Bots will Play ?
I know it depends on the Slots: But when were played an offline/lan WE even can Change any Slots on the Pick Up Screen.
Open Hyper AI fixed it by adding an '!pos!" Command into His Script

**Comment by ryndrb** [comment]
Doing something like that probably requires? each bot to have a build for each position. Adding builds are kinda tedious (not copy-paste as it will feel samey). If someone PRs them, I might consider it. I don't really play offline or on LAN, so it's not really a priority as it's mostly for personal use.

**Comment by ryndrb** [comment]
I will be closing this as there isn't any follow up.
